#!/bin/bash

echo
echo =================	Test 01: 4 2 8 8 0 a8.txt
../a01.out 4 2 8 8 0 a8.txt
echo =================

echo
echo =================	Test 02: 4 1 10 10 0 a2.txt
../a01.out 4 1 10 10 0 a2.txt
echo =================
