#!/bin/bash

echo
echo =================	Test 00: 0 0 0 empty.txt
../a02.out 0 0 0 empty.txt
echo =================

echo
echo =================	Test 01: 6 6 0 01.txt
../a02.out 6 6 0 01.txt
echo =================

echo
echo =================	Test 02: 7 6 1
../a02.out 7 6 1
echo =================

echo
echo =================	Test 03: 7 6 3
../a02.out 7 6 3
echo =================

echo
echo =================	Test 04: 11 11 0 02.txt
../a02.out 11 11 0 02.txt
echo =================

echo
echo =================	Test 05: 3 3 0 04.txt
../a02.out 3 3 0 04.txt
echo =================

echo
echo =================	Test 06: 10000 10 6
../a02.out 10000 10 6
echo =================
