#!/bin/bash

echo
echo =================	Test 00: 3 0 0 0 empty.txt
../a$1.out 1 0 0 0 empty.txt
echo =================

echo
echo =================	Test 01: 2 7 7 0 01.txt
../a$1.out 2 7 7 0 01.txt
echo =================

echo
echo =================	Test 02: -1 7 6 1
../a$1.out -1 7 6 1
echo =================

echo
echo =================	Test 03: 1 7 6 3
../a$1.out 1 7 6 3
echo =================

echo
echo =================	Test 04: 2 11 11 0 02.txt
../a$1.out 2 11 11 0 02.txt
echo =================

echo
echo =================	Test 05: 1 3 3 0 04.txt
../a$1.out 1 3 3 0 04.txt
echo =================

echo
echo =================	Test 06: -11 10000 10 6
../a$1.out -11 10000 10 6
echo =================

echo
echo =================	Test 07: 1 9 9 0 05.txt
../a$1.out 1 9 9 0 05.txt
echo =================

echo
echo =================	Test 08: 1 1 1 0 06.txt
../a$1.out 1 1 1 0 06.txt
echo =================
