double solve1(double *a, int n, int m);
double solve2(double *a, int n, int m);
double solve3(double *a, double *x, double *b, int n, int m);
double solve4(double *a, double *x, double *b, int n, int m);
double solve5(double *a, double *b, int n, int m);
double solve6(double *a, double *b, int n, int m);
double solve7(double *a, int n, int m);
double solve8(double *a, int n, int m);
double solve9(double *a, int n, int m);
double solve10(double *a, int n, int m);
double solve11(double *a, int n, int m);
