#!/bin/bash

echo
echo =================	Test 00: 0 0 0 0 empty.txt
../a03.out 0 0 0 0 empty.txt
echo =================

echo
echo =================	Test 01: 5 10 10 0 a1.txt
../a03.out 5 10 10 0 a1.txt
echo =================

echo
echo =================	Test 02: 0 5 5 1
../a03.out 0 5 5 1
echo =================

echo
echo =================	Test 03: 7 3 3 1
../a03.out 7 3 3 1
echo =================

echo
echo =================	Test 04: 3 2 2 0 a3.txt
../a03.out 3 2 2 0 a3.txt
echo =================

echo
echo =================	Test 05: 5 6 6 0 a4.txt
../a03.out 5 6 6 0 a4.txt
echo =================

echo
echo =================	Test 06: 1 6 6 0 a5.txt
../a03.out 1 6 6 0 a5.txt
echo =================



