#!/bin/bash

echo
echo =================	Test 00: 0 0 0 0 0 0 empty.txt
../a02.out 0 0 0 empty.txt 0 0 0 empty.txt
echo =================

echo
echo =================	Test 01: 10 20 0 a2.txt 6 6 0 b2.txt
../a02.out 10 20 0 a2.txt 6 6 0 b2.txt
echo =================

echo
echo =================	Test 02: 10 20 1 6 6 0 b2.txt
../a02.out 10 20 1 6 6 0 b2.txt
echo =================

echo
echo =================	Test 03: 10 20 0 a2.txt 6 6 3
../a02.out 10 20 0 a2.txt 6 6 3
echo =================

echo
echo =================	Test 04: 5 20 1 5 6 3
../a02.out 5 20 1 5 6 3
echo =================
